site_name: RxDogTag
repo_name: RxDogTag
repo_url: https://github.com/uber/RxDogTag
site_description: "Automatic tagging of RxJava 2 originating subscribe points for onError() investigation."
site_author: Uber Technologies
remote_branch: gh-pages

copyright: 'Copyright &copy; 2019 Uber Technologies'

theme:
  name: 'material'
  favicon: images/uber_oss_logo.png
  logo: images/uber_oss_logo.png
  palette:
    primary: 'white'
    accent: 'white'

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - 'Overview': index.md
  - 'Examples': examples.md
  - 'Under The Hood': under-the-hood.md
  - 'Proguard/R8': shrinking.md
  - 'Changelog' : changelog.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code-of-conduct.md
